<h1>Part 1<h1>

<h1>Task 1</h>

In [1]:
import numpy as np

rng = np.random.default_rng(seed=1)

readings = rng.normal(50, 15, size = (360,4))
print(readings)

[[55.18376288 62.32427215 54.95655614 30.45264153]
 [63.580338   56.69561859 41.94570147 58.71677156]
 [55.46858594 54.41198745 50.42633362 58.2006948 ]
 ...
 [53.11257643 61.28556975 31.96115261 33.79547486]
 [45.32393381 31.74923486 60.34389827 30.00420818]
 [51.02574528 13.12856568 33.42830415 44.91446996]]


In [2]:
print(readings.shape)

(360, 4)


In [3]:
print(readings.dtype)

float64


In [4]:
print(readings[:3,:])

[[55.18376288 62.32427215 54.95655614 30.45264153]
 [63.580338   56.69561859 41.94570147 58.71677156]
 [55.46858594 54.41198745 50.42633362 58.2006948 ]]


<h1>Task 2</h1>

In [5]:
scaled_readings = (readings - readings.min(axis=0)) / (readings.max(axis=0) - readings.min(axis=0))
scaled_readings

array([[0.47297578, 0.61010987, 0.6249914 , 0.27732179],
       [0.55959024, 0.54589717, 0.48524465, 0.60350492],
       [0.47591386, 0.51984509, 0.57633327, 0.59754912],
       ...,
       [0.45161056, 0.59826016, 0.37800278, 0.31589987],
       [0.3712672 , 0.2613043 , 0.68285567, 0.27214663],
       [0.43008396, 0.04887633, 0.39376114, 0.444219  ]], shape=(360, 4))

In [6]:
centered_readings = readings - readings.mean(axis=0)
centered_readings

array([[  5.45260156,  12.38018993,   5.80782034, -18.42273205],
       [ 13.84917668,   6.75153637,  -7.20303433,   9.84139799],
       [  5.73742462,   4.46790523,   1.27759782,   9.32532123],
       ...,
       [  3.38141511,  11.34148753, -17.1875832 , -15.07989871],
       [ -4.40722751, -18.19484736,  11.19516247, -18.8711654 ],
       [  1.29458396, -36.81551654, -15.72043165,  -3.96090362]],
      shape=(360, 4))

<h1>Task 3</h1>

In [7]:
def bool_mask(arr):
    return (arr > 80) | (arr < 20)

def outlier_info(arr):
    mask = bool_mask(arr)
    num_outliers = np.sum(mask)  
    total = arr.size                    
    return {'Number of outliers': num_outliers, 'Fraction of outliers': num_outliers / total}


info = outlier_info(readings)
print(info)


def cleaning(arr):
    arr = arr.copy()
    arr[bool_mask(readings)] = np.nan
    return arr

cleaned_reading = cleaning(readings)
cleaned_reading


{'Number of outliers': np.int64(68), 'Fraction of outliers': np.float64(0.04722222222222222)}


array([[55.18376288, 62.32427215, 54.95655614, 30.45264153],
       [63.580338  , 56.69561859, 41.94570147, 58.71677156],
       [55.46858594, 54.41198745, 50.42633362, 58.2006948 ],
       ...,
       [53.11257643, 61.28556975, 31.96115261, 33.79547486],
       [45.32393381, 31.74923486, 60.34389827, 30.00420818],
       [51.02574528,         nan, 33.42830415, 44.91446996]],
      shape=(360, 4))

In [8]:
num_mask = np.sum(bool_mask(readings))
num_nan = np.isnan(cleaned_reading).sum()
print(f'Number of masks for outliers: {num_mask}\nNumber of NaN: {num_nan}')
print(num_mask == num_nan)

Number of masks for outliers: 68
Number of NaN: 68
True


<h1>Task 4</h1>

In [9]:
sensor_means = np.mean(readings, axis = 0)
print(sensor_means)

[49.73116132 49.94408222 49.1487358  48.87537357]


In [10]:
sensor_stds = np.std(readings, axis = 0)
print(sensor_stds)

[14.47158011 15.29611813 15.45299059 15.20066135]


In [11]:
time_means = np.mean(readings, axis = 1)
print(time_means)

[50.72930818 55.2346074  54.62690045 47.06511074 45.15561745 57.62497777
 30.51073164 55.38793595 61.15599863 42.92898984 39.02234743 48.22440364
 53.70324914 50.1409455  47.4940827  43.38999667 52.72947519 48.24770327
 54.09034562 41.06422662 43.03604134 53.45848209 57.67514642 44.19204546
 45.50678537 52.83021853 47.0440003  54.11669024 52.65653262 47.70129161
 43.06212875 53.31967303 45.6392658  45.69266044 41.04658563 50.9636795
 51.07734794 47.62260038 47.30075334 38.16930761 50.99397213 63.29543993
 47.44193581 47.38518883 50.77692201 59.72575436 46.43114481 47.6791187
 37.53164117 52.85384222 61.83705382 49.64238564 44.70747097 42.09891625
 46.54281107 50.00098875 42.73623483 45.77541351 43.47761069 40.73994857
 44.42801083 51.08282893 48.39014587 48.90484796 47.83740205 38.62277319
 44.94347989 48.84209224 47.05247347 48.75797912 52.28680925 46.45240328
 44.40605099 54.96384854 55.10022211 42.74985945 54.82381755 59.0446795
 42.79247628 43.5808956  42.44103774 41.095398   55.89

In [12]:
print(f'Number of sensor_means: {sensor_means.size}')
print(f'Number of sensor_stds: {sensor_stds.size}')
print(f'Number of time_means: {time_means.size}')

Number of sensor_means: 4
Number of sensor_stds: 4
Number of time_means: 360


<h1>Task 5<h1>

In [13]:
report = {
    'total_readings': readings.size,
    'outlier_count': np.sum(bool_mask(readings)),
    'outlier_percent': np.sum(bool_mask(readings)) / readings.size * 100,
    'sensor_means': np.mean(readings, axis=0),
    'sensor_stds': np.std(readings, axis=0)
}

if report['total_readings'] != readings.size:
    print("Warning: total readings does not match array size!")

report_str = (
    f"Total readings: {report['total_readings']}\n"
    f"Outlier count: {report['outlier_count']}\n"
    f"Outlier percent: {report['outlier_percent']:.2f}%\n"
    f"Sensor means: {report['sensor_means']}\n"
    f"Sensor stds: {report['sensor_stds']}"
)

print(report_str)


Total readings: 1440
Outlier count: 68
Outlier percent: 4.72%
Sensor means: [49.73116132 49.94408222 49.1487358  48.87537357]
Sensor stds: [14.47158011 15.29611813 15.45299059 15.20066135]


<h1>Part 2<h1>

<h1>Task 6<h1>

In [14]:
import numpy as np

rng = np.random.default_rng(seed=1)

sim = rng.normal(0, 1, size = (1000,6))
print(readings)

[[55.18376288 62.32427215 54.95655614 30.45264153]
 [63.580338   56.69561859 41.94570147 58.71677156]
 [55.46858594 54.41198745 50.42633362 58.2006948 ]
 ...
 [53.11257643 61.28556975 31.96115261 33.79547486]
 [45.32393381 31.74923486 60.34389827 30.00420818]
 [51.02574528 13.12856568 33.42830415 44.91446996]]


In [17]:
print(sim.shape)
print(sim.dtype)
print(sim[:3,:])

(1000, 6)
float64
[[ 0.34558419  0.82161814  0.33043708 -1.30315723  0.90535587  0.44637457]
 [-0.53695324  0.5811181   0.3645724   0.2941325   0.02842224  0.54671299]
 [-0.73645409 -0.16290995 -0.48211931  0.59884621  0.03972211 -0.29245675]]


<h1>Task 7</h1>

In [18]:
scenario_shift = [-0.3, -0.1, 0.0, 0.1, 0.2, 0.4]

In [19]:
adjusted_sim = sim + scenario_shift
print(adjusted_sim)

[[ 0.04558419  0.72161814  0.33043708 -1.20315723  1.10535587  0.84637457]
 [-0.83695324  0.4811181   0.3645724   0.3941325   0.22842224  0.94671299]
 [-1.03645409 -0.26290995 -0.48211931  0.69884621  0.23972211  0.10754325]
 ...
 [ 0.34803336  1.03286227  1.32186089  1.13889128  2.06162135 -1.39906033]
 [-0.60893865  0.2183484  -2.24787473 -0.66958975  1.33635491 -0.27069988]
 [ 0.67141932  0.51443615  1.15591292  0.90423714  0.72353969  1.06430979]]


In [23]:
print(f'Shape of original sim: {sim.shape}')
print(f'Shape of adjusted sim: {adjusted_sim.shape}')
print(sim.shape == adjusted_sim.shape)

Shape of original sim: (1000, 6)
Shape of adjusted sim: (1000, 6)
True


<h1>Task 8<h1>

In [26]:
scenario_means = adjusted_sim.mean(axis=0) 
print("Scenario means:", scenario_means)

ranking = np.argsort(scenario_means)
print("Ranking of scenarios (lowest to highest):", ranking)

top2_partition = np.partition(scenario_means, -2)[-2:]
print("Top 2 scenario means (partition):", top2_partition)

top2_sorted = np.sort(scenario_means)[-2:]
print("Top 2 scenario means (full sort):", top2_sorted)

print('Matching: ',np.all(np.isin(top2_partition, top2_sorted)))

Scenario means: [-0.29993845 -0.15789841 -0.03687076  0.13866868  0.2632746   0.34589908]
Ranking of scenarios (lowest to highest): [0 1 2 3 4 5]
Top 2 scenario means (partition): [0.2632746  0.34589908]
Top 2 scenario means (full sort): [0.2632746  0.34589908]
Matching:  True


<h1>Task 9<h1>

In [27]:
rng_same = np.random.default_rng(seed=1)
sim_2 = rng_same.normal(0, 1, size=(1000, 6))

print("sim and sim_2 are equal:", np.array_equal(sim, sim_2))
print("Number of matching elements:", np.sum(sim == sim_2))  

sim and sim_2 are equal: True
Number of matching elements: 6000


In [29]:
rng_diff = np.random.default_rng(seed=2)
sim_3 = rng_diff.normal(0, 1, size=(1000, 6))

print("sim and sim_3 are approximately equal (np.allclose):", np.allclose(sim, sim_3))
print("Number of matching elements with different seed:", np.sum(sim == sim_3))

sim and sim_3 are approximately equal (np.allclose): False
Number of matching elements with different seed: 0


<h1>Task 10</h1>

In [ ]:
top_two_indices = np.argsort(scenario_means)[-2:]  
top_two_values = scenario_means[top_two_indices] 

validation_report = {
    'shape': adjusted_sim.shape,
    'scenario_means': scenario_means,
    'top_two_indices': top_two_indices,
    'top_two_values': top_two_values
}

assert len(scenario_means) == 6, "scenario_means should have length 6"
assert len(top_two_indices) == 2, "top_two_indices should have length 2"

report_str = (
    f"Shape of adjusted_sim: {validation_report['shape']}\n"
    f"Scenario means: {validation_report['scenario_means']}\n"
    f"Indices of top 2 scenarios: {validation_report['top_two_indices']}\n"
    f"Values of top 2 scenarios: {validation_report['top_two_values']}"
)

print(report_str)

Validation Report:
- Shape of adjusted_sim: (1000, 6)
- Scenario means: [-0.29993845 -0.15789841 -0.03687076  0.13866868  0.2632746   0.34589908]
- Indices of top 2 scenarios: [4 5]
- Values of top 2 scenarios: [0.2632746  0.34589908]
